### ISSUE TITLE
Linux Compatability

### ISSUE THREAD

**Issue by radioaddition** [Catterall/Scambaiting-Setup#10]
is there a way to do what vboxsysteminfo does manually? I'm running the vm on a linux machine so that tool won't work for me

**Comment by kosude** [comment]
There is a Linux adaptation of vBoxSystem info available at [OnePlusOneIsTu/vBoxSysInfoMod-Linux](https://github.com/OnePlusOneIsTu/vBoxSysInfoMod-Linux); this worked well for me.
