### ISSUE TITLE
What are the list of Tools?

### ISSUE THREAD

**Issue by jennyjanetech** [Catterall/Scambaiting-Setup#11]
What specific RAT do scambaiters stars in youtube use? and can you please list down the tools so i can install it in my vbox.

**Comment by xSerpentineX** [comment]
I don't know what RATs specifically they use. Some popular options are Dark Comet, Nanocore, etc.

However, if you know what you are doing you can also program your own RAT, though this requires technical expertise and some good knowledge in making sure this doesn't also reveal your own device.

I believe Dark Comet is paid, though I do not know. Nanocore is also paid.
