### ISSUE TITLE
The link 'Windows 10 ISO file' under 'Creating a new Virtual Machine' has no way to download an ISO file.

### ISSUE THREAD

**Issue by dimani128** [Catterall/Scambaiting-Setup#12]
As far as I can tell, the link 'Windows 10 ISO file' under ['Creating a new Virtual Machine'](https://github.com/xSerpentineX/Scambaiting-Setup#creating-a-new-virtual-machine) has no obvious way to download a .iso file.

**Comment by xSerpentineX** [comment]
Download the creation media
